created react to do app with passing props.
SteveBehm/react-javascript-projects pull request #1
Opened 2022-05-29 23:45 UTC by SteveBehm

![Uploading Screen Shot 2022-05-29 at 4.43.08 PM.png…]()

2022-05-29 23:57 UTC, thebearingedge requested changes

2022-05-29 23:57 UTC, thebearingedge commented on react-to-do-app/src/components/todo-list.js
> +  }
You can leave out the `[...todos]` here and just do `todos.filter()` because `filter` does not modify the original array.

2022-05-30 00:00 UTC, thebearingedge requested changes

2022-05-30 00:00 UTC, thebearingedge commented on react-to-do-app/src/components/todo-list.js
> +  }
It's best not to modify your objects but instead just return them or make modified copies.
```js
  const completeTodo = id => {
    const updatedTodos = todos.map(todo => {
      return todo.id === id
        ? { ...todo, isComplete: !todo.isComplete }
        : todo
    })
    setTodos(updatedTodos);
  }
```

2022-05-30 18:59 UTC, SteveBehm commented
<img width="775" alt="Screen Shot 2022-05-29 at 4 43 08 PM" src="https://user-images.githubusercontent.com/96929704/171048007-6cbd47c7-eae7-408f-bfb7-1c0f60edb190.png">

2022-05-30 19:00 UTC, thebearingedge approved these changes

2022-05-30 19:05 UTC, merged